### ISSUE TITLE
Destructuring Assignemnts with require sometimes break

### ISSUE THREAD

**Issue by marcmenn** [decaffeinate/decaffeinate#528] opened 2016-11-09 12:50 UTC
decaffeinate is crashing on my CoffeeScript input:

```coffee
{foo} = require('bar').x
```

http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=%7Bfoo%7D%20%3D%20require('bar').x%0A

I get this error:

```
Property local of ImportSpecifier expected node to be of a type ["Identifier"] but instead got "ObjectPattern"
```

**Comment by alangpierce** [comment] 2016-11-12 06:58
Thanks for reporting. This is a duplicate of #404, so closing in favor of that one.

**Closed by alangpierce** 2016-11-12 06:58 UTC
