### ISSUE TITLE
Destructuring assignment in function doesn't compile at all

### ISSUE THREAD

**Issue by edi9999** [decaffeinate/decaffeinate#254] opened 2016-06-19 13:15 UTC
```
class TableManager
  constructor:(@tables=@tables)->
    console.log(1)
```

gives an error.

**Comment by madskonradsen** [comment] 2016-07-23 09:19
Dupe of #232 ?

**Comment by alangpierce** [comment] 2016-10-23 18:39
Looks like this is fixed now: [repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=class%20TableManager%0A%20%20constructor%3A(%40tables%3D%40tables)-%3E%0A%20%20%20%20console.log(1))

**Closed by alangpierce** 2016-10-23 18:39 UTC
