### ISSUE TITLE
Exporting an object with methods crashes decaffeinate

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#281] opened 2016-07-05 04:03 UTC
Here's a simple example:
```
module.exports = {
  a: ->
    return
}
```
http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=true&code=module.exports%20%3D%20%7B%0A%20%20a%3A%20-%3E%0A%20%20%20%20return%0A%7D

The actual error is "Cannot read property 'name' of undefined". I tried tracking the issue down and it looks like the crash is happening because esnext is trying to create a named export called `a`, but it only supports identifiers, not functions, as export values. This is mentioned in a esnext bug: https://github.com/esnext/esnext/issues/92#issuecomment-224725435 .

It seems like an easy correct behavior, at least in the meantime, is to forget about the named export and just do `export default`, something like this:
```
export default {
  a() {}
}
```
The module would need a default export like that to stay compatible with existing usages anyway, right? (I'm not sure how the different module systems interact with each other, so I might be wrong there.) Maybe decaffeinate could pass a flag to tell esnext to be less ambitious, or we could just change esnext for now.

This is the third most common decaffeinate error in my codebase (after for loop expressions and soaked member access), with 57 out of 1339 files failing for this reason, so it would be great to get something working.

**Comment by madskonradsen** [comment] 2016-07-08 14:24
Duplicate of #256 ?

**Comment by eventualbuddha** [comment] 2016-07-12 16:32
Yes, this is a duplicate of #256.

**Closed by eventualbuddha** 2016-07-12 16:32 UTC
