### ISSUE TITLE
Emits ending-square-bracket in the wrong place

### ISSUE THREAD

**Issue by madskonradsen** [decaffeinate/decaffeinate#371] opened 2016-08-08 12:49 UTC
decaffeinate is crashing on my CoffeeScript input:

```coffee
SomeArr = [ ->
    if something
      lol =
        count: 7
  ]
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&code=SomeArr%20%3D%20%5B%20-%3E%0A%20%20%20%20if%20something%0A%20%20%20%20%20%20lol%20%3D%0A%20%20%20%20%20%20%20%20count%3A%207%0A%20%20%5D)
I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (6:2)
  4 |         {count: 7};
  5 |     }
> 6 |   ]
    |   ^
  7 |   };
```

**Comment by alangpierce** [comment] 2016-08-10 03:06
Looks to me like this is another bug in the CoffeeScript parser. MainStage emits the function `}` after the `]` [(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=MainStage&code=SomeArr%20%3D%20%5B%20-%3E%0A%20%20%20%20if%20something%0A%20%20%20%20%20%20lol%20%3D%0A%20%20%20%20%20%20%20%20count%3A%207%0A%20%20%5D), but it looks like the root cause is that the CoffeeScript AST shows the Code (i.e. function expression) body as ending at position 5:4, which is just after the `]` [(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=coffeescript-parser&code=SomeArr%20%3D%20%5B%20-%3E%0A%20%20%20%20if%20something%0A%20%20%20%20%20%20lol%20%3D%0A%20%20%20%20%20%20%20%20count%3A%207%0A%20%20%5D).

**Comment by alangpierce** [comment] 2016-08-10 16:57
Ok, I have a fix for this. [Here it is in the repl for my fork.](http://www.alangpierce.com/decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=SomeArr%20%3D%20%5B%20-%3E%0A%20%20%20%20if%20something%0A%20%20%20%20%20%20lol%20%3D%0A%20%20%20%20%20%20%20%20count%3A%207%0A%20%20%5D) I'll clean it up and send out a PR when I get a chance.

**Comment by madskonradsen** [comment] 2016-08-10 16:59
Was it necessary to fix the bug in the CoffeeScript parser? In that case it would probably take a looong time before it gets merged into their master-branch :(

**Comment by alangpierce** [comment] 2016-08-10 17:05
Yep, the fix was in the CoffeeScript lexer/parser. We recently set up a decaffeinate-specific fork of CoffeeScript (https://github.com/decaffeinate/coffeescript), and decaffeinate now depends on the [decaffeinate-coffeescript](https://www.npmjs.com/package/decaffeinate-coffeescript) package, so fortunately everything is now in place for us to make patches to CoffeeScript without having to wait for an official release. See https://github.com/decaffeinate/decaffeinate/issues/356 for more context.

**Comment by alangpierce** [comment] 2016-08-14 00:38
Fixed with https://github.com/decaffeinate/coffeescript/pull/4.

**Closed by alangpierce** 2016-08-14 00:38 UTC
