### ISSUE TITLE
yarn?

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#1047] opened 2017-05-28 21:48 UTC
I've stared using [yarn](https://yarnpkg.com/en/) on my other projects and like it pretty well. Should decaffeinate use it? Alternatively, [npm v5 just landed](http://blog.npmjs.org/post/161081169345/v500), which supposedly includes a lockfile that actually works (unlike npm-shrinkwrap.json).

What do you think, @alangpierce?

**Comment by alangpierce** [comment] 2017-05-28 23:18
Yep, I use yarn at work now and certainly am a fan of it. Switching to yarn just means committing the lockfile, right? I just tested and it can install everything just fine as-is.

In the decaffeinate case, I'm a little hesitant since I actually sort of like being able to do minor/patch releases on project like decaffeinate-parser, coffee-lex, and esnext without having to do another commit on the decaffeinate side to pick it up. Although I suppose if there was a greenkeeper PR it would be pretty easy. Looks like greenkeeper just added yarn support a few days ago ( https://github.com/greenkeeperio/greenkeeper/issues/314 , https://github.com/greenkeeperio/greenkeeper-lockfile ), so hopefully all of that would just work.

**Comment by alangpierce** [comment] 2017-06-25 18:43
After reading https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/ , I'm still a little skeptical of some of the ideas (it seems maybe best to use the latest non-dev dependencies on every build), but overall it seems pretty reasonable to use yarn for decaffeinate itself and commit the lockfile.

Some notes:
* The decaffeinate lockfile will NOT affect anyone installing decaffeinate. The normal semver ranges will apply, or if decaffeinate is installed in a project with a lockfile, decaffeinate's dependencies will be locked down via that lockfile.
* The daily decaffeinate-examples build installs decaffeinate normally (not from source), so any regressions will hopefully be caught there.
* The travis build already didn't update dependencies to latest due to the npm cache; I've generally had to bump the package.json dependencies to get the build to pick up new versions.
* Supposedly greenkeeper should still catch issues. It looks like there's a bug with it ( https://github.com/decaffeinate/decaffeinate-parser/issues/196 ), but hopefully that should be fixed soon.
* The main benefit of the lockfile is to lock down development dependencies, which does seem useful. As the article correctly points out, there are a lot more dev dependencies than normal dependencies.

**Closed** 2017-07-05 23:13 UTC
Labels: question
