### ISSUE TITLE
Decaffeinate fails if file is comment only.

### ISSUE THREAD

**Issue by hauleth** [decaffeinate/decaffeinate#400] opened 2016-09-02 12:32 UTC
Decaffeinate is crashing on my CoffeeScript input:

```coffee
# a
```

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%23%20a

I get this error:

```
unexpected 'null' index, perhaps you forgot to check the result of 'indexOfTokenContainingSourceIndex'?
```

**Comment by alangpierce** [comment] 2016-09-03 03:51
Thanks for the report! This is a duplicate of #352, so closing in favor of that one.

**Closed by alangpierce** 2016-09-03 03:51 UTC
