### ISSUE TITLE
no patcher available for node type: SoakedDynamicMemberAccessOp

### ISSUE THREAD

**Issue by sethyates** [decaffeinate/decaffeinate#216] opened 2016-05-14 11:13 UTC
```
$ echo 'myObject?[myKey]' | decaffeinate
stdin: no patcher available for node type: SoakedDynamicMemberAccessOp (props: expression, indexingExpr)
> 1 | myObject?[myKey]
    | ^^^^^^^^^^^^^^^^
  2 |
```

**Comment by madskonradsen** [comment] 2016-05-14 11:27
Kind of dupe of #176 
Join our discussion

**Comment by sethyates** [comment] 2016-05-14 11:32
Kind of, but different error message and different application type, and I didn't see this particular use case listed when I looked at that issue (I did check before raising).  I don't know anything about the parser/patcher, so it might be a different code path as well.

**Comment by eventualbuddha** [comment] 2016-05-25 17:17
It's essentially the same as #176, but I'll leave it open to people can find it more easily.

**Closed** 2016-07-19 23:16 UTC
Labels: bug, duplicate
