### ISSUE TITLE
Fresh install of decaffeinate is throwing a babel compile error

### ISSUE THREAD

**Issue by jbcorry** [decaffeinate/decaffeinate#2407] opened 2021-08-18 21:44 UTC
decaffeinate is crashing on my CoffeeScript input:

```coffee
language = "coffeescript"
```

https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&optionalChaining=false&evaluate=true&stage=full&code=language%20%3D%20%22coffeescript%22

I get this error:

```
Error: Plugin conflict between `["pipelineOperator", { proposal: "smart" }]` and `["recordAndtuple", { syntaxType: "hash"}]`.
Only getting this locally, not on the repl
```

**Comment by jbcorry** [comment] 2021-08-18 21:46
I am not able to even run decaffeinate on this simple line of coffeescript.  I suspect it is a local babel issue, but my colleagues are getting the same error.  Any suggestions?

**Comment by corporealshift** [comment] 2021-08-19 13:46
I am having the same error on any coffeescript files

**Comment by eventualbuddha** [comment] 2021-08-19 13:59
Thanks for the report. I’m looking into it.

**Comment by Lucaszw** [comment] 2021-08-19 14:00
Im having this issue as well.. very strange

**Comment by eventualbuddha** [comment] 2021-08-19 14:06
I've reproduced the error with both 14.15.4 and current LTS 14.17.5. It does not happen with 12.19.0 (what I usually run) and latest 16.7.0. I'll investigate more later, but this may unblock you for now.

**Comment by corporealshift** [comment] 2021-08-19 14:17
I just tried this with node 12.19.0 and had the same error. I also tried it in a docker image with node:latest (to hopefully avoid local problems) and got the same error

**Comment by eventualbuddha** [comment] 2021-08-19 14:20
Perhaps something about which exact Babel versions are being installed… I'll look more.

**Comment by eventualbuddha** [comment] 2021-08-19 16:21
It seems likely this was broken by https://github.com/babel/babel/pull/13191, which means babel 7.15.x probably broke some assumptions made by `@codemod/parser`. I've reproduced the error there and will issue a fix.

**Comment by eventualbuddha** [comment] 2021-08-19 20:44
Alright, I believe this is fixed now since decaffeinate depends on `@codemod/parser@^1.1.0`, which should pull in `1.1.1` which I just published. If it's still not working feel free to comment again.

**Closed by eventualbuddha** 2021-08-19 20:44 UTC

**Comment by corporealshift** [comment] 2021-08-19 20:49
ty for being so responsive

**Comment by jbcorry** [comment] 2021-08-19 22:18
Thank you very much @eventualbuddha!  That fixed the issue.
