### ISSUE TITLE
Chaining function calls on separate lines generates invalid JS

### ISSUE THREAD

**Issue by christopherthielen** [decaffeinate/decaffeinate#63] opened 2015-10-02 16:51 UTC
see: http://bit.ly/1M6tUYk
This coffeescript:
```
$stateProvider
.state 'foo'
.state 'bar'
```
should generate something like `$stateProvider.state('foo').state('bar');`

It generates invalid JS:
```
$stateProvider
.state( 'foo'
.state( 'bar'
)
);
```

**Comment by christopherthielen** [comment] 2015-10-02 19:29
dupe #51

**Comment by eventualbuddha** [comment] 2015-10-03 15:37
Believe it or not this isn't a dupe of #51. The parsing seems to be happening correctly but decaffeinate isn't inserting the parentheses in the right place.

**Comment by eventualbuddha** [comment] 2016-04-30 01:15
Fixed in the latest version ([repl](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=%24stateProvider%0A.state%20'foo'%0A.state%20'bar')).

**Closed by eventualbuddha** 2016-04-30 01:15 UTC
Labels: bug
