### ISSUE TITLE
Non-last splat crashing in AddVariableDeclarationsStage

### ISSUE THREAD

**Issue by niieani** [decaffeinate/decaffeinate#545] opened 2016-11-14 01:19 UTC
decaffeinate is crashing on my CoffeeScript input:

```coffee
(args..., funcArg) -> new Map {}
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=(args...%2C%20funcArg)%20-%3E%20new%20Map%20%7B%7D)

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token, expected ) (1:17)
> 1 | (function(...args, funcArg) { return new Map({}); });
```

Correct output: http://coffeescript.org/#try:(args...%2C%20funcArg)%20-%3E%20new%20Map%20%7B%7D

**Comment by alangpierce** [comment] 2016-11-14 01:26
Thanks. Looks like this is a duplicate of #107, so closing in favor of that.

**Closed by alangpierce** 2016-11-14 01:26 UTC

**Comment by niieani** [comment] 2016-11-14 01:33
Sorry, didn't see that one! 

Thanks 👍
