### ISSUE TITLE
Invalid conversion of static/class properties

### ISSUE THREAD

**Issue by mitar** [decaffeinate/decaffeinate#123] opened 2016-02-09 23:18 UTC
``` coffee
class MainLayoutComponent extends BlazeLayoutComponent
  @register 'MainLayoutComponent'

  @REGIONS:
    MAIN: 'main'

  renderMain: (parentComponent) ->
    @_renderRegion @constructor.REGIONS.MAIN, parentComponent
```

is converted to:

``` js
class MainLayoutComponent extends BlazeLayoutComponent {
  this.register('MainLayoutComponent');

  this.REGIONS:
    {MAIN: 'main'}

  ;renderMain(parentComponent) {
    return this._renderRegion(this.constructor.REGIONS.MAIN, parentComponent);
  }
}
```

This is clearly invalid.

**Comment by eventualbuddha** [comment] 2016-02-25 04:51
Yep. In fact, this may not really be convertible to an ES class at all. Probably the closest thing would be this:

```js
class MainLayoutComponent extends BlazeLayoutComponent {
  static REGIONS = { MAIN: 'main' };

  renderMain(parentComponent) {
    return this._renderRegion(this.constructor.REGIONS.MAIN, parentComponent);
  }
}

MainLayoutComponent.register('MainLayoutComponent');
```

What do you think?

**Comment by mitar** [comment] 2016-02-25 05:07
```
static REGIONS = { MAIN: 'main' };
```

is to my knowledge invalid. ES6 classes can only contain methods, not properties.

I know of two solutions:

```
class MainLayoutComponent extends BlazeLayoutComponent {
  static get REGIONS() { return { MAIN: 'main' } };

  renderMain(parentComponent) {
    return this._renderRegion(this.constructor.REGIONS.MAIN, parentComponent);
  }
}

MainLayoutComponent.register('MainLayoutComponent');
```

Or:

```
class MainLayoutComponent extends BlazeLayoutComponent {
  renderMain(parentComponent) {
    return this._renderRegion(this.constructor.REGIONS.MAIN, parentComponent);
  }
}

MainLayoutComponent.REGIONS = { MAIN: 'main' };

MainLayoutComponent.register('MainLayoutComponent');
```

**Comment by eventualbuddha** [comment] 2016-02-25 05:25
ES6 classes can only contain methods, but ES7 will (likely?) have properties. [Here's the code I suggested in the babel repl](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20MainLayoutComponent%20extends%20BlazeLayoutComponent%20%7B%0A%20%20static%20REGIONS%20%3D%20%7B%20MAIN%3A%20'main'%20%7D%3B%0A%0A%20%20renderMain(parentComponent)%20%7B%0A%20%20%20%20return%20this._renderRegion(this.constructor.REGIONS.MAIN%2C%20parentComponent)%3B%0A%20%20%7D%0A%7D)

**Comment by eventualbuddha** [comment] 2016-02-25 05:28
As for the `@register` call, I believe there's no way to realistically reproduce that without falling back to functions and prototypes, since subsequent prototype assignments or calls may depend on that call having happened in its particular part of the source.

**Comment by mitar** [comment] 2016-02-25 05:33
> I believe there's no way to realistically reproduce that without falling back to functions and prototypes, since subsequent prototype assignments or calls may depend on that call having happened in its particular part of the source.

What if the order of the call would not matter? Can we do something better than just calling it at the end?

**Comment by mitar** [comment] 2016-02-25 05:33
> ES6 classes can only contain methods, but ES7 will (likely?) have properties.

Oh, finally! :-)

**Comment by eventualbuddha** [comment] 2016-02-25 05:34
> What if the order of the call would not matter? Can we do something better than just calling it at the end?

Maybe, but in not sure what it'd be.

**Comment by alangpierce** [comment] 2016-10-30 20:55
Closing now that #397 has landed. The example now converts to correct code that uses a static method to do the initialization work: [repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=class%20MainLayoutComponent%20extends%20BlazeLayoutComponent%0A%20%20%40register%20'MainLayoutComponent'%0A%0A%20%20%40REGIONS%3A%0A%20%20%20%20MAIN%3A%20'main'%0A%0A%20%20renderMain%3A%20(parentComponent)%20-%3E%0A%20%20%20%20%40_renderRegion%20%40constructor.REGIONS.MAIN%2C%20parentComponent).

**Closed by alangpierce** 2016-10-30 20:55 UTC
Labels: bug
