### ISSUE TITLE
POST-IF within else branch produces error

### ISSUE THREAD

**Issue by thebanjomatic** [decaffeinate/decaffeinate#306] opened 2016-07-12 21:10 UTC
I have stripped down the following reproducer from a more complicated example:

```coffee
if someCondition
   `// intentionally blank`
else
   x = abc if xyz
```

produces the error:
```
expected IF token at start of conditional, but got IDENTIFIER
  2 |    `// intentionally blank`
  3 | else
> 4 |    x = abc if xyz
    |    ^^^^^^^^^^^^^^
  5 | 
```

[REPL Reproducer](http://decaffeinate-project.org/repl/#?evaluate=true&code=if%20someCondition%0D%0A%20%20%20%60%2F%2F%20intentionally%20blank%60%0D%0Aelse%0D%0A%20%20%20x%20%3D%20abc%20if%20xyz%0D%0A)

Manually transforming the code into the following has worked thus-far, however, the problem has started to show up enough that the manual transformations have been very time consuming:

```coffee
if someCondition
   `// intentionally blank`
else
   if xyz then x = abc
```

**Comment by eventualbuddha** [comment] 2016-07-12 22:25
Duplicate of #275

**Closed by eventualbuddha** 2016-07-12 22:25 UTC
